#define FILE_TILES	L"tiles.bmp"
#define FILE_UNPLUGGED	L"unplugged.bmp"
#define FILE_MENU	L"menu.bmp"
#define FILE_MENU_TEXT	L"menu-text.bmp"
#define FILE_MANUAL_01	L"manual01.bmp"
#define FILE_MANUAL_02	L"manual02.bmp"
#define FILE_MANUAL_03	L"manual03.bmp"
#define FILE_MANUAL_04	L"manual04.bmp"
#define FILE_MANUAL_05	L"manual05.bmp"
#define FILE_PANEL	L"panel.bmp"
#define FILE_BIGNUM	L"bignum.bmp"
#define FILE_SMALLNUM	L"smallnum.bmp"
#define FILE_GAME_OVER	L"game-over.bmp"
#define FILE_GAME_WIN	L"game-last.bmp"
#define FILE_OBJECTIVE	L"objective.bmp"
#define FILE_STATUS	L"status.bmp"
#define FILE_MICRO_FONT	L"micro-font.bmp"
#define FILE_HISCORES	L"hiscores.bmp"
#define FILE_ABOUT	L"about.bmp"
#define FILE_MENU_HIGHLIGHT	L"menu-highlight.bmp"
#define FILE_MANUAL_BUTTONS	L"manual-buttons.bmp"

#define FILE_RECHARGE	L"recharge.wav"
#define FILE_ALARM	L"alarm.wav"
#define FILE_FATAL	L"fatal.wav"
#define FILE_QUANT	L"quant.wav"
#define FILE_DISCHARGE	L"discharge.wav"
#define FILE_BOOM	L"boom.wav"

#define FILE_RECORDS_MUSIC	L"records.wav"
#define FILE_MANUAL_MUSIC	L"manual.wav"
#define FILE_MENU_MUSIC		L"menu.wav"
#define FILE_ABOUT_MUSIC	L"about.wav"

#define FILE_L10N_STR	L"localization.str"
#define FILE_DEBUG	L"debug.log"
