#define FILE_TILES	L"tiles.png"
#define FILE_UNPLUGGED	L"unplugged.png"
#define FILE_MENU	L"menu.png"
#define FILE_MENU_TEXT	L"menu-text.png"
#define FILE_MANUAL_01	L"manual01.png"
#define FILE_MANUAL_02	L"manual02.png"
#define FILE_MANUAL_03	L"manual03.png"
#define FILE_MANUAL_04	L"manual04.png"
#define FILE_MANUAL_05	L"manual05.png"
#define FILE_MANUAL_06	L"manual06.png"
#define FILE_PANEL	L"panel.png"
#define FILE_BIGNUM	L"bignum.png"
#define FILE_SMALLNUM	L"smallnum.png"
#define FILE_GAME_OVER	L"game-over.png"
#define FILE_GAME_WIN	L"game-last.png"
#define FILE_OBJECTIVE	L"objective.png"
#define FILE_STATUS	L"status.png"
#define FILE_MICRO_FONT	L"micro-font.png"
#define FILE_HISCORES	L"hiscores.png"
#define FILE_ABOUT	L"about.png"
#define FILE_MENU_HIGHLIGHT	L"menu-highlight.png"
#define FILE_MANUAL_BUTTONS	L"manual-buttons.png"

#define FILE_RECHARGE	L"recharge.wav"
#define FILE_ALARM	L"alarm.wav"
#define FILE_FATAL	L"fatal.wav"
#define FILE_QUANT	L"quant.wav"
#define FILE_DISCHARGE	L"discharge.wav"
#define FILE_BOOM	L"boom.wav"

#define FILE_RECORDS_MUSIC	L"records.wav"
#define FILE_MANUAL_MUSIC	L"manual.wav"
#define FILE_MENU_MUSIC		L"menu.wav"
#define FILE_ABOUT_MUSIC	L"about.wav"

#define FILE_L10N_STR	L"localization.str"
#define FILE_DEBUG	L"debug.log"
